// Tabla de equivalencias español-inglés para ingredientes comunes
const INGREDIENT_EQUIVALENCE = {
  'café': 'coffee',
  'chocolate': 'chocolate',
  'fresas': 'strawberries',
  'fresa': 'strawberry',
  'ajo': 'garlic',
  'leche': 'milk',
  'huevos': 'eggs',
  'huevo': 'egg',
  'patatas': 'potatoes',
  'patata': 'potato',
  'manzana': 'apple',
  'manzanas': 'apples',
  'pera': 'pear',
  'peras': 'pears',
  'kiwi': 'kiwi',
  'lomo': 'loin',
  'calabacín': 'zucchini',
  'cerveza': 'beer',
  'arroz': 'rice',
  'pollo': 'chicken',
  'pescado': 'fish',
  'carne': 'meat',
  'tomate': 'tomato',
  'tomates': 'tomatoes',
  'aceite': 'oil',
  'sal': 'salt',
  'azúcar': 'sugar',
  'pan': 'bread',
  'queso': 'cheese',
  'mantequilla': 'butter',
  'cebolla': 'onion',
  'pimiento': 'pepper',
  'zanahoria': 'carrot',
  'naranja': 'orange',
  'plátano': 'banana',
  'banana': 'banana',
  'uva': 'grape',
  'uvas': 'grapes',
  'limón': 'lemon',
  'limones': 'lemons',
  'maíz': 'corn',
  'atún': 'tuna',
  'yogur': 'yogurt',
  'zanahorias': 'carrots',
  'pepino': 'cucumber',
  'pepinos': 'cucumbers',
  'espinaca': 'spinach',
  'espinacas': 'spinach',
  'calabaza': 'pumpkin',
  'calabazas': 'pumpkins',
  'miel': 'honey',
  'avena': 'oats',
  'almendra': 'almond',
  'almendras': 'almonds',
  'nuez': 'walnut',
  'nueces': 'walnuts',
  'pistacho': 'pistachio',
  'pistachos': 'pistachios',
  'avellana': 'hazelnut',
  'avellanas': 'hazelnuts',
  'coco': 'coconut',
  'canela': 'cinnamon',
  'vainilla': 'vanilla',
  'clavo': 'clove',
  'clavos': 'cloves',
  'perejil': 'parsley',
  'cilantro': 'cilantro',
  'albahaca': 'basil',
  'oregano': 'oregano',
  'romero': 'rosemary',
  'tomillo': 'thyme',
  'laurel': 'bay leaf',
  'mostaza': 'mustard',
  'mayonesa': 'mayonnaise',
  'ketchup': 'ketchup',
  'salsa': 'sauce',
  'vinagre': 'vinegar',
  'agua': 'water',
  'hielo': 'ice',
  'gambas': 'shrimp',
  'langostinos': 'prawns',
  'mejillones': 'mussels',
  'almejas': 'clams',
  'calamares': 'squid',
  'pulpo': 'octopus',
  'bacalao': 'cod',
  'merluza': 'hake',
  'salmón': 'salmon',
  'trucha': 'trout',
  'ternera': 'beef',
  'cerdo': 'pork',
  'cordero': 'lamb',
  'pavo': 'turkey',
  'conejo': 'rabbit',
  'hamburguesa': 'burger',
  'salchicha': 'sausage',
  'salchichas': 'sausages',
  'jamón': 'ham',
  'chorizo': 'chorizo',
  'morcilla': 'blood sausage',
  'lentejas': 'lentils',
  'garbanzos': 'chickpeas',
  'judías': 'beans',
  'alubias': 'beans',
  'soja': 'soy',
  'tofu': 'tofu',
  'seta': 'mushroom',
  'setas': 'mushrooms',
  'champiñón': 'mushroom',
  'champiñones': 'mushrooms',
  'espaguetis': 'spaghetti',
  'macarrones': 'macaroni',
  'fideos': 'noodles',
  'pasta': 'pasta',
  'pizza': 'pizza',
  'lasagna': 'lasagna',
  'tarta': 'cake',
  'bizcocho': 'sponge cake',
  'galleta': 'cookie',
  'galletas': 'cookies',
  'helado': 'ice cream',
  'flan': 'flan',
  'natillas': 'custard',
  'mousse': 'mousse',
  'turrón': 'nougat',
  'mazapán': 'marzipan',
  'polvorón': 'shortbread',
  'rosquilla': 'doughnut',
  'rosquillas': 'doughnuts',
  'churro': 'churro',
  'churros': 'churros',
  'tostada': 'toast',
  'tostadas': 'toasts',
  'croissant': 'croissant',
  'magdalena': 'muffin',
  'magdalenas': 'muffins',
  'bollito': 'bun',
  'bollitos': 'buns',
  'panecillo': 'roll',
  'panecillos': 'rolls',
  'empanada': 'pie',
  'empanadas': 'pies',
  'tortilla': 'omelette',
  'tortillas': 'omelettes',
  'crepe': 'crepe',
  'crepes': 'crepes',
  'quiche': 'quiche',
  'soufflé': 'souffle',
  'brownie': 'brownie',
  'brownies': 'brownies',
  'muffin': 'muffin',
  'muffins': 'muffins',
  'baguette': 'baguette',
  'ciabatta': 'ciabatta',
  'focaccia': 'focaccia',
  'pita': 'pita',
  'naan': 'naan',
  'pretzel': 'pretzel',
  'donut': 'donut',
  'donuts': 'donuts',
  'cruasán': 'croissant',
  'cruasanes': 'croissants',
  'bollería': 'pastry',
  'bollos': 'buns',
  'panadería': 'bakery',
  'pastelería': 'pastry shop',
  'dulce': 'sweet',
  'dulces': 'sweets',
  'postre': 'dessert',
  'postres': 'desserts',
};
import fetch from 'node-fetch';

const GOOGLE_TRANSLATE_API_KEY = process.env.GOOGLE_TRANSLATE_API_KEY;

export async function translateIngredients(ingredients, targetLang = 'en') {
  if (!GOOGLE_TRANSLATE_API_KEY) throw new Error('Falta GOOGLE_TRANSLATE_API_KEY');
  if (!Array.isArray(ingredients) || ingredients.length === 0) return [];
  // Primero, aplicar equivalencias manuales
  const mapped = ingredients.map(i => INGREDIENT_EQUIVALENCE[i.toLowerCase()] || i);
  // Si todos los ingredientes ya están en inglés, no traducir
  if (mapped.every((v, idx) => v !== ingredients[idx])) {
    return mapped;
  }
  // Traducir solo los que no están en la tabla
  const toTranslate = mapped.filter((v, idx) => v === ingredients[idx]);
  if (toTranslate.length === 0) return mapped;
  const url = `https://translation.googleapis.com/language/translate/v2?key=${GOOGLE_TRANSLATE_API_KEY}`;
  const body = {
    q: toTranslate,
    target: targetLang,
    format: 'text'
  };
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body)
  });
  const data = await response.json();
  if (!data.data || !data.data.translations) return mapped;
  // Reemplazar solo los traducidos
  let idx = 0;
  return mapped.map((v, i) => (v === ingredients[i] ? data.data.translations[idx++].translatedText.toLowerCase() : v));
}